# Generated by Django 2.2 on 2019-04-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('doing', 'doing'), ('done', 'done'), ('cancer', 'cancer')], default='doing', max_length=20)),
            ],
        ),
    ]
